# needs to be configured properly where yaml is parsed with pyyaml

eureka:
  ssl: true
  host: localhost
  ipAddress: 127.0.0.1
  port: 10011
  servicePath: '/eureka'
  maxRetries: 30
  requestRetryDelay: 1000
  registryFetchInterval: 5


instance:
  app: pythonservice
  vipAddress: pythonservice
  instanceId: localhost:pythonservice:10018
  homePageUrl: https://localhost:10018/
  hostName: 'localhost'
  ipAddr: '127.0.0.1'
  secureVipAddress: pythonservice
  port:
    $: 10018
    '@enabled': false
  securePort:
    $: 10018
    '@enabled': true

  dataCenterInfo:
    '@class': com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo
    name: MyOwn
  metadata:
    apiml.catalog.tile.id: 'cademoapps'
    apiml.catalog.tile.title: 'Sample Python Hello World'
    apiml.catalog.tile.description: 'Applications Hello'
    apiml.routes.api_v1.gatewayUrl: "api/v1"
    apiml.routes.api_v1.serviceUrl: "/api/v1"
    apiml.apiInfo.0.apiId: org.zowe.pythonservice
    apiml.apiInfo.0.gatewayUrl: "api/v1"
    apiml.apiInfo.0.swaggerUrl: https://localhost:10018/swagger.json
    apiml.service.title: 'Zowe Sample Node Service'
    apiml.service.description: 'The Proxy Server is an HTTP HTTPS, and Websocket server built upon NodeJS and ExpressJS.'

ssl:
  enabled: true
  certificate: ../keystore/localhost/localhost.keystore.cer
  keystore: ../keystore/localhost/localhost.keystore.key
  caFile: ../keystore/localhost/localhost.pem
  keyPassword: password
