instance:
    host: localhost
    ipAddress: localhost
    homePageUrl: http://localhost:10018/python_enabler_service
    statusPageUrl: /application/info
    port: "10018"
    metadata:
        apiml.catalog.tile.id: pythonen
        apiml.catalog.tile.title: Python Enabler Service
        apiml.catalog.tile.description: A sample python enabler used for onboarding
        apiml.catalog.tile.version: 1.0.1
        apiml.routes.api_v1.gatewayUrl: api/v1
        apiml.routes.api_v1.serviceUrl: /
        apiml.service.id: PYTHON_ENABLER_SERVICE
        apiml.service.title: My Python Enabler
        apiml.service.description: sample python enabler
        apiml.apiInfo.0.swaggerUrl: http://localhost:10018/pythonSwagger.json
        apiml.apiInfo.0.apiId: zowe.python.enabler
        apiml.apiInfo.0.version: 1.0.1
